In [1]:
# module - single python file
# packages - collection of multiple such modules stored in a folder
# libraries - collection of multiple packages and modules

In [2]:
# numpy, pandas, seaborn, matplotlib

In [4]:
# numpy - numerical python
# library - mathematical computations, 
# numbers, lists, large amount of numbers very fast
# matrices

In [5]:
pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
# arrays - collection of data of only one type and ttypically numbers

In [8]:
# creation

In [9]:
a = np.array([1,2,3,4,5])
# am using array function of np to create a array

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
type(a)

numpy.ndarray

In [12]:
# array - one data type at a time
# lists - can store multiple data types

In [14]:
a1 = np.array([1.1,2.1,3.11])
a1

array([1.1 , 2.1 , 3.11])

In [15]:
type(a1)

numpy.ndarray

In [17]:
# datatype of elements inside a numpy array

In [16]:
a1.dtype

dtype('float64')

In [18]:
a.dtype

dtype('int64')

In [19]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [20]:
z.dtype

dtype('float64')

In [21]:
z1 = np.zeros(5,dtype = 'int')

In [22]:
z1

array([0, 0, 0, 0, 0])

In [23]:
z1.dtype

dtype('int64')

In [27]:
np.ones(9,dtype = 'int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# 8s - 10

In [32]:
np.full(10,8)

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [33]:
# create an array with a range of values

In [34]:
# np.arange(start,stop,step)

In [36]:
np.arange(8,18,2)

array([ 8, 10, 12, 14, 16])

In [38]:
# Creates evenly spaced values

In [37]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
# size and dimmension

In [41]:
a = np.array([0,8,9,7,2,0,4,5])

In [42]:
a

array([0, 8, 9, 7, 2, 0, 4, 5])

In [43]:
type(a)

numpy.ndarray

In [44]:
# ndarray - N-dimensional array

In [46]:
# shape (number of rows and columns)
# dimmension (number of dimensions ) 
# size (total number of elements )

In [47]:
a

array([0, 8, 9, 7, 2, 0, 4, 5])

In [48]:
a.shape

(8,)

In [49]:
# 8 elements in a single row

In [50]:
a.ndim

1

In [53]:
a.size

8

In [54]:
# total 8 elements in a

In [55]:
a2 = np.array([[1,2,3],[5,6,7]])
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [56]:
a2.shape

(2, 3)

In [57]:
# 2 rows, 3 columns

In [58]:
a2.ndim

2

In [59]:
a2.size

6

In [60]:
# Total elements = 2 × 3

In [61]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
a3.shape

(2, 2, 3)

In [64]:
# 2 blocks, 2 rows, 3 columns

In [65]:
a3.ndim

3

In [66]:
a3.size

12

In [68]:
# Total elements = 2 × 2 × 3

In [69]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
a3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
# Converts multi-dimensional array into 1D

In [73]:
# numpy arrays - broadcasting - arrays of different shapes to be used in arithmetic operations without
# explicit looping

In [74]:
b = np.array([1,2,3,4,5,6,7,8])
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
b.size

8

In [76]:
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
b.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
b.reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [80]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
b+5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [82]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [83]:
[9,8,7]*2

[9, 8, 7, 9, 8, 7]

In [85]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[4,5,8],[9,8,7]])

In [86]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
d

array([[4, 5, 8],
       [9, 8, 7]])

In [88]:
c+d

array([[ 5,  7, 11],
       [13, 13, 13]])

In [90]:
e = np.array([[3,4],[9,8]])
e

array([[3, 4],
       [9, 8]])

In [91]:
c+e

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [92]:
# with broadcasting, NumPy automatically expands the 
# smaller array to match the larger one without actually copying data.

In [93]:
a

array([0, 8, 9, 7, 2, 0, 4, 5])

In [94]:
b = np.ones(8,dtype = int)
b

array([1, 1, 1, 1, 1, 1, 1, 1])

In [95]:
a+b

array([ 1,  9, 10,  8,  3,  1,  5,  6])

In [96]:
a = np.array([1,2,3])
b = np.array([[10],[20]])

In [97]:
a

array([1, 2, 3])

In [98]:
b

array([[10],
       [20]])

In [99]:
a+b

array([[11, 12, 13],
       [21, 22, 23]])

In [100]:
# 1️⃣ If the dimensions are equal, NumPy proceeds normally.
# 2️⃣ If one array has size 1 in a dimension, it is stretched 
# to match the other.
# 3️⃣ If the dimensions are different and neither is 1, 
# NumPy throws an error.

In [101]:
g = np.array([[1, 2, 3], [4, 5, 6]])

In [102]:
g

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
g+8

array([[ 9, 10, 11],
       [12, 13, 14]])

In [104]:
# 8 here is scalar value

In [105]:
b

array([[10],
       [20]])

In [106]:
b[1]

array([20])

In [107]:
a

array([1, 2, 3])

In [108]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [110]:
np.sin(c)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [111]:
np.cos(c)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [112]:
np.power(c,5)

array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [113]:
# statistical functions

In [114]:
np.mean(c)

3.5

In [115]:
np.median(c)

3.5

In [116]:
np.std(c)

1.707825127659933

In [117]:
np.var(c)

2.9166666666666665

In [118]:
np.max(c)

6

In [119]:
np.min(c)

1

In [120]:
# product of all elements present in a array

In [121]:
np.prod(c)

720

In [123]:
s = np.array([8,9,7,1,2,45,2,0])

In [124]:
s

array([ 8,  9,  7,  1,  2, 45,  2,  0])

In [125]:
np.sort(s)

array([ 0,  1,  2,  2,  7,  8,  9, 45])

In [126]:
# max value

In [127]:
np.max(s)

45

In [128]:
# index of max value

In [129]:
np.argmax(s)

5

In [130]:
np.argmin(s)

7

In [131]:
s

array([ 8,  9,  7,  1,  2, 45,  2,  0])

In [132]:
# Splits an array into n parts

In [137]:
d,f = np.split(s,2)

In [138]:
d

array([8, 9, 7, 1])

In [139]:
f

array([ 2, 45,  2,  0])

In [136]:
# You have a sorted NumPy array of numbers. 
# Given a target value, find the closest number in the array.

In [140]:
m = np.array([1, 3, 7, 10, 15, 20])
m

array([ 1,  3,  7, 10, 15, 20])

In [141]:
t = 8

In [144]:
index = np.abs(m-t).argmin()

In [145]:
m[index]

7

In [147]:
# Pandas - data analysis and manipulation

In [148]:
pip install pandas


[notice] A new release of pip is available: 23.3.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [149]:
import pandas as pd

In [151]:
# data structure - series( Like a single column in a table (1D)) 
# dataframe - Like a full table with rows & columns (2D)

In [152]:
# pandas series

In [153]:
d = pd.Series([10,20,30,29,10,18])
d

0    10
1    20
2    30
3    29
4    10
5    18
dtype: int64

In [154]:
type(d)

pandas.core.series.Series

In [155]:
# custom index

In [158]:
d = pd.Series([10,20,30,29,10,18],index = ['a','b','c','d','e','f'])
d

a    10
b    20
c    30
d    29
e    10
f    18
dtype: int64

In [159]:
d['a']

10

In [160]:
d['c']

30

In [164]:
# index position - iloc - integer location

In [163]:
d.iloc[0]

10

In [165]:
d.iloc[3]

29

In [166]:
# access by labels/indices

In [167]:
d['a']

10

In [168]:
d.loc['a']

10

In [169]:
d[['a','c']]

a    10
c    30
dtype: int64

In [170]:
d.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [171]:
# modify series

In [172]:
d['a'] = 100

In [173]:
d

a    100
b     20
c     30
d     29
e     10
f     18
dtype: int64

In [174]:
d['g'] = 200

In [175]:
d

a    100
b     20
c     30
d     29
e     10
f     18
g    200
dtype: int64

In [176]:
# filter data

In [177]:
d[d>20]

a    100
c     30
d     29
g    200
dtype: int64

In [178]:
d>20

a     True
b    False
c     True
d     True
e    False
f    False
g     True
dtype: bool

In [179]:
# delete a value

In [180]:
d.drop('b')

a    100
c     30
d     29
e     10
f     18
g    200
dtype: int64

In [181]:
# operations

In [182]:
d

a    100
b     20
c     30
d     29
e     10
f     18
g    200
dtype: int64

In [183]:
d+9

a    109
b     29
c     39
d     38
e     19
f     27
g    209
dtype: int64

In [184]:
d*7

a     700
b     140
c     210
d     203
e      70
f     126
g    1400
dtype: int64

In [190]:
y = d.apply(lambda x:x*5)

In [191]:
y

a     500
b     100
c     150
d     145
e      50
f      90
g    1000
dtype: int64

In [187]:
# check for nulls

In [188]:
d.isnull()

a    False
b    False
c    False
d    False
e    False
f    False
g    False
dtype: bool

In [189]:
d

a    100
b     20
c     30
d     29
e     10
f     18
g    200
dtype: int64